# This is a basic workflow to help you get started with Actions

name: release-packages

env:
  LAB_NPM_TOKEN: ${{ secrets.LAB_NPM_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PERSONAL_TOKEN: ${{ secrets.GH_TOKEN }}

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ['release', 'beta', 'alpha']

  workflow_dispatch:
    inputs:
      branch:
        description: 'Frontend branch'
        required: false
        default: 'release'
        type: choice
        options:
          - release
          - alpha

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Show env
        run: |
          echo $RELEASE_VERSION

      - name: Install dependencies
        run: |
          pnpm install

      - name: Build packages
        run: pnpm run build

      - name: Set npm registry
        run: |
          npm config set registry https://registry.npmjs.com/
          npm config set //registry.npmjs.com/:_authToken ${NPM_TOKEN}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install-2
        with:
          version: 7
          run_install: false
      - name: Publish packages
        run: pnpm run release
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

      - name: Trigger release frontend workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: release-frontend
          inputs: |
            {
              "branch": "${{ github.event.inputs.branch }}"
            }
